### PR TITLE
Fix server URLs

### PR DESCRIPTION
**Pull request by bebatut**
Thanks for the list.

I tried to fix the URL. But there is also other issues with the servers:
- Not up
   - http://galaxy.cbiit.cuhk.edu.hk/ is not up
- In maintenance
    - http://services.cbib.u-bordeaux2.fr/galaxy/ is 
- Requires an API authentication
    - http://whaleshark.georgiaaquarium.org
    - http://lisis.cs.ucy.ac.cy/

### CODE REVIEW

**Comment by bebatut** [comment]
Other issues with the servers:
- Not up
   - http://galaxy.cbiit.cuhk.edu.hk/ is not up
- In maintenance
    - http://services.cbib.u-bordeaux2.fr/galaxy/ is 
- Requires an API authentication
    - http://whaleshark.georgiaaquarium.org
    - http://lisis.cs.ucy.ac.cy/

**Comment by martenson** [comment]
@bebatut the servers will be down and up, one of the use cases I would like to cover is a live table of uptime (I think @erasche was interested in this too)

By API authentication do you mean require login? That is one column in the table.

**Comment by hexylena** [comment]
@martenson yep, definitely! Do you have plans for implementing this in the near term? It seems like a relatively small project to build a webpage for it :)

**Comment by martenson** [comment]
@erasche I will gather the data into csv for now (basically waiting if someone wants to contribute this)

**Comment by hexylena** [comment]
ok, I'll contribute a UI tonight then, if that's ok.

**Comment by martenson** [comment]
@erasche tonight feels a bit late but....alright then `</VERY_STRONG_IRONY>`

**Comment by bebatut** [comment]
@erasche Is a webpage for that not redundant with the Hub page about the public servers?

**Comment by hexylena** [comment]
if this one tracks uptime ... maybe not redundant. If it wasn't for that goal, then yeah, I'd definitely agree that hub should just use this dataset

**Comment by martenson** [comment]
we want uptimes, versions, tool lists and maybe other properties of public server - none of these are static so hub is not a good place for building it, it might be a good place to hosting the output of such though

**Pull request merged**
