### PR TITLE
Remove truly offline instances + decrease false-negative rate.

### PR DESCRIPTION
**Pull request by hexylena**

### CODE REVIEW

**Comment by martenson** [comment]
I am not sure about the definition  of `truly offline` here.

**Comment by hexylena** [comment]
they have not responded at any point in the past 30 days. I manually checked each one again / looked up their website root directories to ensure it wasn't available under a different path / etc. 

(Sorry, if I'd thought you were going to review this I would have left it un-merged)

**Comment by martenson** [comment]
@erasche maybe we have wrong url, maybe they moved, maybe they are gonna be offline for 100 days...

Should we have a long_term_offline (or similar) flag instead, is it worth tracking?

**Comment by hexylena** [comment]
Yeah, I tried to check the wrong URL / moving case as much as I could. I can email the registered support contact for these servers if you'd like?

We could flag long_term_offline, but this seems relatively unappealing from the perspective of "why are we track this under the  'public-server-list' if they aren't available for public use".

**Comment by martenson** [comment]
@erasche If we are sure they are dead, we should relay this information to @tnabtaf since we shouldn't advertise servers that are not operational :/

**Comment by hexylena** [comment]
agreed. If you'd prefer I can re-add those servers, move them to the bottom and flag them somehow? We could keep checking in with them.

Also what are your thoughts on servers with external auth? My thoughts are:
- We'll never know if they're online or offline (Or if galaxy is even running behind the auth dialog)
- There's never a "please go here for information about our server" it's just a dialog of "Credentials or gtfo" which I don't believe we should be advertising under the list of "public servers" where people really should be able to just show up and use.

**Comment by martenson** [comment]
@erasche some of the auth'd servers have open registration I think, so the auth page itself is not helpful, but the server is. For purposes of the list this state sucks. :/

**Comment by tnabtaf** [comment]
@erasche @martenson I'm about half-way through my quarterly process of dropping dead servers.  I've heard back from some of the ones I contacted, but not yet others.  I wrote to everyone last Wednesday.  Give me until the end of the week to drop anything that isn't up, or isn't expected to be up soon.

*EDIT:* Just noticed that this is not in the Hub repo.  All my comments apply to the list in the hub repo.  With apologies.

**Comment by hexylena** [comment]
@tnabtaf hey that's great. We'll do something about re-syncing [the list](https://github.com/martenson/public-galaxy-servers/pull/14/files#diff-60cfb35af09ec627db63c7568ae63998) whenever you've got your downed servers removed.

**Comment by tnabtaf** [comment]
Here's my status as of today:

* Down, but expected to return sometime soon
  * Ballaxy, Image Analysis & Processing Tookit
* Was down, but back up:
  * Orione, In Silico, RDF2Graph
* Down, status unknown (I'll drop these):
  * MetaDP, NGS-QC
* Down for good (I've dropped):
  * Bistro
* Will be down for a while but will return (dropped for now)
  * ODOSE
* Closer to up:
  * Pia, Osiris

**Comment by tnabtaf** [comment]
Dropped MetaDP and NGS-QC from Galaxy Hub directory.  Not planning on any other changes this month.

**Pull request merged**
