### PR TITLE
Scraper

### PR DESCRIPTION
**Pull request by hexylena**
- added scraper
- should be put on cron
- rewrote servers.csv to remove information that will be redundant with these results files
- Example output

```json
  {
    "code": 200,
    "features": {
      "allow_user_creation": true,
      "allow_user_dataset_purge": true,
      "brand": "GVL 4.0.1",
      "enable_unique_workflow_defaults": true,
      "ga_code": null,
      "message_box_visible": false,
      "require_login": false,
      "terms_url": null,
      "use_remote_user": false
    },
    "homepage": true,
    "response_time": 10.616418,
    "server": "https://galaxy-qld.genome.edu.au/galaxy",
    "version": "16.04"
  },
```

### CODE REVIEW

**Comment by hexylena** [comment]
- since I can't edit the comment because github is being slow, there are probably still some false "downs" that should be investigated.

**Comment by martenson** [comment]
might be relevant to know how old are `/api/configuration` and `/api/version` endpoints

**Comment by martenson** [comment]
Also not every galaxy that is tagged as `registration_required` is using the `allow_user_creation` or `require_login` config. Some have custom regs and/or external authentication.

**Comment by hexylena** [comment]
- `/api/configuration` is older than `/api/version` which is why I only use `configuration`.
- We get different responses depending on if they're there or not, but everything that is `up`, is reporting it truly. no false positives as far as I can tell. 15.10 is the earliest that I see in the responses.

```
      2 "15.10"
     16 "16.01"
     12 "16.04"
      7 "16.07"
      5 "16.10"
     13 "17.01"
      9 "17.05"
     43 null
```

- at least one server on the list doesn't have either endpoint (and it is recorded as 'up', but without a lot of information. We still have no way of inferring version, but yes we could manually annotate registration required or not.)
- anything using external authentication shows up with `use_remote_user` and we can inherently assume registration is required, since I don't know of a single auth provider that would allow anonymous users.
- Yes automatic falls short on some old servers, but .. they're ancient, they're beyond the security horizon, I'm not sure we should even push users towards them by saying "yes, go here, reg is available"
- sigh, you have a fair point though, maybe this should support some way to override registration required `:|`

**Review by martenson — APPROVED** [review]
this is awesome

**Pull request merged**
